-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
-- 단, 보호기간이 긴 순으로 정렬하여 조회

-- ANIMAL_INS와 ANIMAL_OUTS를 JOIN 한다음
-- ANIMAL_OUTS.DATETIME = ANIMAL_INS.DATETIME
-- 보호기간이 긴 순이므로 DESC

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
-- WHERE OUTS.DATETIME IS NOT NULL -- 없어도 OK -- 입양을 갔으므로 우선 INS는 무조건 있을 거고 OUTS도 무조건 있을 것 
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS, ANIMAL_INS INS
WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID 
-- AND OUTS.DATETIME IS NOT NULL -- INS에 있어도 OUTS에 없으면 아예 JOIN하지 않으므로 필요없는 듯?
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;
