-- 09:00부터 19:59까지 각 시간대별로 입양이 몇건이나 발생했는지 조회하는 SQL문
-- 결과는 시간대 순으로 정렬

-- SELECT * FROM ANIMAL_OUTS
-- ORDER BY HOUR(DATETIME);

SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);

SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19 -- HOUR(DATETIME)이 아닌 HOUR
ORDER BY HOUR(DATETIME);
