-- ANIMAL_OUTS의 DATETIME(입양일)이 ANIMAL_INS의 DATETIME(보호일) 보다 빠른(작은) 경우
-- 단, 보호일 빠른(작은)순으로 정렬

-- LEFT OUTER JOIN 사용
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME;

-- RIGHT OUTER JOIN 사용
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS RIGHT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME;

-- 전형적인 JOIN 사용
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS, ANIMAL_INS INS
WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID
AND OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME;
