-- ANIMAL_INS에서는 중성화되지 않았지만, ANIMAL_OUTS에서는 중성화된 동물
-- 단, ANIMAL_ID 순서대로 정렬하여 출력
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND INS.SEX_UPON_INTAKE LIKE 'Intact%'
AND OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%' 
ORDER BY OUTS.ANIMAL_ID;
