-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 ANIMAL_ID, NAME
-- ANIMAL_ID 순으로 정렬

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS RIGHT OUTER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID -- ON 조건 반드시 필요!
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID;
