-- ANIMAL_INS 테이블에서 ANIMAL_ID 순서대로
-- ANIMAL_TYPE, NAME, SEX_UPON_TAKE를 출력하되
-- NAME이 NULL일 경우 No name으로 치환
SELECT ANIMAL_TYPE, IFNULL(NAME,'No name'), SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
