-- ANIMAL_INS 테이블에서 가장 먼저 들어온(DATETIME이 가장 빠른) 동물의 NAME을 출력
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS);

-- MySQL
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1;

-- LIMIT 3 : 1~3 레코드 조회
-- LIMIT 2,6: 2~6 레코드 조회
