-- 우유와 요거트 동시에 구입한 장바구니
-- 단, 장바구니 아이디 순으로
SELECT DISTINCT(CART_ID) 
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk')
AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt')
ORDER BY CART_ID;

SELECT DISTINCT(A.CART_ID) FROM 
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') as A, 
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') as B
WHERE A.CART_ID = B.CART_ID
 
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk' AND 
CART_ID IN (SELECT DISTINCT CART_ID
            FROM CART_PRODUCTS
            WHERE NAME = 'Yogurt')
ORDER BY CART_ID
