SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.DATETIME IS NOT NULL 
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS, ANIMAL_INS INS
WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID 
-- AND OUTS.DATETIME IS NOT NULL -- INS에 있어도 OUTS에 없으면 아예 JOIN하지 않으므로 필요없는 듯?
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;
